### ISSUE TITLE
When extracting the reference csi and tof measurements, the routers often reboots automatically.

### ISSUE THREAD

**Issue by crownz-sec** [IMDEANetworksWNG/UbiLocate#25]
At first, I connect antenna 1 of two routers. Then I extracting CSI using 1*4 configuration. After that, I start to extract ToF. Because it will happen the problem in #22 , I executes the  scripts on routers. Finally, I execute `bash start_tof.sh name` on pc. But the script blocks during the data saving phase, just like following image.
<img width="689" alt="tof_problem" src="https://user-images.githubusercontent.com/47936479/146773556-e2f195b6-2d8a-446c-bf1f-625ec9376239.png">
And after the block occurs for a while, the router will reboot, which means I need to retrieve the benchmark CSI again. I've tried it five times, it's been the same every time. So I can't get tof data corresponding to the reference CSI. 
What's the reason? It's a really annoying problem.

**Comment by alejandroBlancoPizarro** [comment]
Hi,

The problem with the rebooting could be that you executed more than one time reload.sh. If you execute two times reload, the router will reboot automatically. We are not sure about this behavior.

I recommend you to take CSI and ToF measurements separately if that is possible. If not possible, let me know.

Best,
Alejandro

**Comment by crownz-sec** [comment]
Intuitively, it is possible to separate CSI and ToF measurements. But if the environment is changing dynamically, is there a mismatch between CSI and ToF measurements? How to deal with that?

I also have a thought that if executing a script to extract CSI and ToF at the same time is not feasible. Can I use the 4X4 MIMO packets obtained every 32 packets by the ToF script as the reference CSI in the case of using coaxial cable and power divider? After that, disconnecting the coaxial cable and using antenna to transmit and receive. Finally, the subsequent 4X4 MIMO packets were calibrated using the previously obtained reference CSI. Is this right?

**Comment by alejandroBlancoPizarro** [comment]
Hi,

My answer below:

*Can I use the 4X4 MIMO packets obtained every 32 packets by the ToF script as the reference CSI in the case of using coaxial cable and power divider?*

Yes, you can do it. The idea of extracting from time to time the CSI is to enable a join extraction of tof and CSI. 


*Finally, the subsequent 4X4 MIMO packets could be calibrated using previously obtained reference CSI. Is this right?*
Yes, you are totally correct.

One thing that we observed is that when the receiver is doing ToF, it sends packets and this may change the phase difference across antennas. But, we have observed that at the transmitter side it does not change. So, if the Angle of Arrival (AoA) at the receiver side it is not as accurate as it should be, I would suggest you to try Angle of Departure (AoD). For computing the AoD, you have to invert the roles, so that the AP is the transmitter and the client is the receiver. 

Let me know if you need further clarification :)

Best,
Alejandro

**Comment by crownz-sec** [comment]
Thanks for your reply, I solved the puzzle. But I still have questions about your last statement. 

I don't know why should I invert the roles for computing AoD when there are phase difference across antennas. I can't figure out the difference between the two cases, can you explain it in more detail? Thanks.

**Comment by alejandroBlancoPizarro** [comment]
Hi,

We observed that for the ToF case, every router is sending packets and this affects the physical configuration at the receiver side; the calibration might be lost for computing AoA. But we also observed that the calibration for AoD is stable.

Typically, the AoA is estimated on the receiver side once a packet is coming from the client. My suggestion is different, I would suggest you to compute the AoD of the AP. To do so, the AoD is computed on the client side from the packets that were sent by the AP. 

Let me know if you need further clarification.

Best,
Alejandro

**Comment by crownz-sec** [comment]
I think I got it, the purpose of inverting the roles is to calculate AoD, and then the AoD of AP can be regarded as AoA previously used for localization. Thanks for reply !
