### ISSUE TITLE
Is it possible for this project to support real-time processing packages?

### ISSUE THREAD

**Issue by crownz-sec** [IMDEANetworksWNG/UbiLocate#27]
I want to try real time processing, so I wonder if I can make some modifications to handle packets sent from the device in real time.

**Comment by alejandroBlancoPizarro** [comment]
Hi,

That might be possible yes. One thing that I can do is to provide a collector which is Network Time Protocol (NTP) compliant so that the traces are saved on the server and not on the router. In that case, you have to extract CSI from the server while the  routers are collecting.

Best,
Alejandro

**Comment by crownz-sec** [comment]
Okay, I see. Thanks for your reply.

**Comment by alejandroBlancoPizarro** [comment]
Let me know if you will need it. 

Best,
Alejandro

**Comment by crownz-sec** [comment]
Okay. I have some ideas about it before, but after consideration, I think I don't need them yet. I'll ask for your help if I need it. Thanks for your reply!
