### ISSUE TITLE
how to configure the ${txchains}

### ISSUE THREAD

**Issue by HuangZengt** [IMDEANetworksWNG/UbiLocate#3]
Thanks for your work. 
Now I want to know how to configure the ${txchains} in hard_scipts/config.sh if I plan to achieve 1x4 MIMO and 4x4 MIMO respectively. 
I will appreciate for your help.

**Comment by alejandroBlancoPizarro** [comment]
Hi,

Thanks for noticing it. It was a bug in the code. I've just fixed in the project. txchain is just a bit mask to control how many antennas transmit. txchain 1 means 1 TX antenna, 3 means 2 TX antennas, 7 means 3 and 15 means 4.

For 1x4 txchain has to be 1 and for 4x4 has to be 15.

Please, update your project by doing git pull

Best,
Alejandro

**Comment by HuangZengt** [comment]
Thanks for your help.
However, our experiments show that when txchains is set to 0x01, all the antennas at the transmitter will transmit signals,&nbsp; does it influence the data transmited by the rightmost antenna and lead to the error of the angle estimation.



Best regards,
Zeng Huang

**Comment by alejandroBlancoPizarro** [comment]
Hi,

Please, at the moment use this command instead:

wl -i eth6 txcore -k 1 -o 1 -s 1 -c 1

Best,
Alejandro

**Comment by HuangZengt** [comment]
Thanks !!!
