### ISSUE TITLE
the distance between two adjacent antennas

### ISSUE THREAD

**Issue by hyunhi2** [IMDEANetworksWNG/UbiLocate#8]
Thank you for your great work!

I'm trying to make 4 RF-chains in the picture below.
What is the distance between two adjacent antennas?
It would be a great help if you could share the drawing of the acrylic plate and other specification.
(diameter of the hole, antenna model, ...)

Thanks in advance

![image](https://user-images.githubusercontent.com/68750363/134636571-f770835d-de74-4c76-b758-15cea8b039dd.png)

**Comment by alejandroBlancoPizarro** [comment]
Hi hyunhi2,

The antenna spacing is half the wavelength. The frequency that we used in our experiment was 5775 MHz.

The base was made of methacrylate with a width of 3mm. The antennas were the ones that came with the Asus. The diameter of the whole was 6.5mm so that you can introduce the [adapter](https://www.digikey.es/product-detail/es/amphenol-rf-division/132170/ACX1244-ND/1011921)

Let me know if you need something more.

Best,
Alejandro

**Comment by hyunhi2** [comment]
Thanks!
Then, if the channel on which the AP operates is changed, does estimated AoA from the code become inaccurate?

**Comment by alejandroBlancoPizarro** [comment]
It is likely to happen this yes. The antenna spacing is not optimized so the aoa accuracy will be degraded but not sure how much.

**Comment by hyunhi2** [comment]
Thank you so much!
